# Generated by Django 3.2 on 2023-04-15 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfomationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=511)),
                ('address', models.CharField(max_length=1023)),
                ('phone_number', models.CharField(max_length=10)),
                ('identity_card', models.CharField(max_length=20)),
                ('place_of_issue_of_identity_card', models.CharField(max_length=511)),
                ('date_of_issue_of_identity_card', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('date_joined', models.DateField()),
                ('salary', models.IntegerField()),
                ('transaction_discount', models.FloatField()),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Nhân viên'), ('collaborators', 'Cộng tác viên')], max_length=127)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('infomation_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.infomationdetail')),
                ('permissions', models.ManyToManyField(to='user.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('permissions', models.ManyToManyField(to='user.Permission')),
            ],
        ),
    ]
