# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-15 08:59

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_authenticated",
            field=models.BooleanField(default=True),
        ),
    ]
