# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-17 16:45

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permissions",
            field=models.ManyToManyField(blank=True, null=True, to="user.Permission"),
        ),
    ]
