# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-03 07:25

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20230422_0920"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
    ]
