# Generated by Django 3.2 on 2023-06-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomationdetail',
            name='gender',
        ),
    ]
