# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-22 16:09

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_remove_infomationdetail_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="infomationdetail",
            name="gender",
            field=models.IntegerField(choices=[(1, "Nam"), (2, "Nữ"), (3, "Khác")], default=1),
        ),
    ]
