# Generated by Django 3.2 on 2023-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_infomationdetail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomationdetail',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Khác')], default=1),
        ),
    ]
