# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-04 08:43

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_infomationdetail_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infomationdetail",
            name="transaction_discount",
            field=models.FloatField(default=0),
        ),
    ]
