# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 07:26

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_infomationdetail_transaction_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_anonymous",
        ),
        migrations.RemoveField(
            model_name="user",
            name="permissions",
        ),
        migrations.AddField(
            model_name="infomationdetail",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="infomationdetail",
            name="identity_card_back_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/user/"),
        ),
        migrations.AddField(
            model_name="infomationdetail",
            name="identity_card_front_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/user/"),
        ),
        migrations.AddField(
            model_name="infomationdetail",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/user/"),
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
