# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 03:50

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_auto_20230724_1426"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
