# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 03:50

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Admin"), (2, "Nhân viên"), (3, "Quản lý"), (4, "Kế toán")], default=2
            ),
        ),
    ]
