# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-10-02 18:35

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Admin"), (2, "Nhân viên"), (3, "Quản lý"), (4, "Kế toán"), (5, "Kế toán trưởng")],
                default=2,
            ),
        ),
    ]
