 repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
        exclude: '.bureauresp$'
      - id: flake8
      - id: trailing-whitespace
        exclude: '.bureauresp$'
  - repo: https://github.com/miki725/importanize
    rev: '0.7'
    hooks:
      - id: importanize
        language_version: python3
        args: [ --verbose ]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ --line-length=120, --safe ]
        language_version: python3
