from django.urls import path

from .views import (
    HomeView,
    SwipeCardView,
    StoreView,
    StoreDetailView,
    StoreDetailDeleteView,
    StoresView,
    POSesView,
    POSView,
    POSDetailView,
    POSDetailDeleteView,
    EmployeeView,
    EmployeesView,
    EmployeeDetailView,
    EmployeeDetailDeleteView,
    StoreCardStorageView,
    StoreCardStorageDetailView,
    StoreCardNotebookDetailView,
    NotebooksView,
    NotebookView,
    NoteBookDetailView,
    NotebookDetailDeleteView,
    UnsavedCard,
    Test,
    InformationDetailAPIView,
    EmployeesListCreateAPIView,
    EmployeeDetailRetrieveUpdateDestroyAPIView,
    StoreListCreateAPIView,
    StoreListCreateAPIViewNoPagination,
    StoreDetailRetrieveUpdateDestroyAPIView,
    POSListCreateAPIView,
    POSDetailRetrieveUpdateDestroyAPIView,
    NotebookListCreateAPIView,
    NoteBookDetailRetrieveUpdateDestroyAPIView,
    CustomerAPIView,
)

from apps.store.views import (
    TransactionHistory,
)

urlpatterns = [
    path('api/notebooks/', NotebookListCreateAPIView.as_view(), name="notebooks"),
    path('api/notebooks/<pk>/', NoteBookDetailRetrieveUpdateDestroyAPIView.as_view(), name="notebook-detail"),
    path('api/poses/', POSListCreateAPIView.as_view(), name="poses"),
    path('api/poses/<pk>/', POSDetailRetrieveUpdateDestroyAPIView.as_view(), name="pos-detail"),
    path('api/stores/', StoreListCreateAPIView.as_view(), name="stores"),
    path('api/stores/nopagination/', StoreListCreateAPIViewNoPagination.as_view(), name="stores"),
    path('api/stores/<pk>/', StoreDetailRetrieveUpdateDestroyAPIView.as_view(), name="stores-detail"),
    path('api/employees/', EmployeesListCreateAPIView.as_view(), name="employees"),
    path('api/employees/<pk>/', EmployeeDetailRetrieveUpdateDestroyAPIView.as_view(), name="employee-detail"),
    path('api/user/infomation-detail/', InformationDetailAPIView.as_view(), name="user-information-detail"),
    path('api/customer/', CustomerAPIView.as_view(), name="customer"),
    # path('', HomeView.as_view(), name="home"),
    # path('unsavedcard/', UnsavedCard.as_view(), name="unsavedcard"),
    # path('swipecard/', SwipeCardView.as_view(), name="swipecard"),
    # path('storecard/store/', StoreCardStorageView.as_view(), name="storecard"),
    # path('storecard/store/<int:store_id>/', StoreCardStorageDetailView.as_view(), name="storecard-store-detail"),
    # path('storecard/notebook/<int:notebook_id>/', StoreCardNotebookDetailView.as_view(), name="storecard-notebook-detail"),
    # path('add_store/', StoreView.as_view(), name="add_store"),
    ## path('stores/', StoresView.as_view(), name="stores"),
    ## path('stores/<pk>/', StoreDetailView.as_view(), name="store-detail"),
    ## path('stores/<pk>/delete/', StoreDetailDeleteView.as_view(), name="delete-store"),
    # path('add_pos/', POSView.as_view(), name="add_pos"),
    # path('poses/', POSesView.as_view(), name="poses"),
    # path('add_pos/<pk>/', POSDetailView.as_view(), name="pos-detail"),
    # path('add_pos/<pk>/delete/', POSDetailDeleteView.as_view(), name="delete-pos"),
    # path('notebooks/', NotebooksView.as_view(), name="notebooks"),
    # path('add_notebook/', NotebookView.as_view(), name="add_notebook"),
    # path('add_notebook/<pk>/', NoteBookDetailView.as_view(), name="notebook-detail"),
    # path('add_notebook/<pk>/delete/', NotebookDetailDeleteView.as_view(), name="delete-notebook"),
    ## path('employees/', EmployeesView.as_view(), name="employees"),
    # path('add_employee/', EmployeeView.as_view(), name="add_employee"),
    ## path('employees/<pk>/', EmployeeDetailView.as_view(), name="employee-detail"),
    ## path('employees/<pk>/delete/', EmployeeDetailDeleteView.as_view(), name="delete-employee"),
    # path('transaction-history/', TransactionHistory.as_view(), name="transaction-history"),
    # path('test/', Test.as_view(), name="test"),
]