# Generated by Django 3.2 on 2023-04-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=127)),
                ('note', models.TextField()),
                ('address', models.CharField(max_length=1023)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_id', models.CharField(max_length=127)),
                ('mid', models.CharField(max_length=127)),
                ('tid', models.CharField(max_length=127)),
                ('note', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=127)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poses', to='store.store')),
            ],
        ),
    ]
