# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-22 06:00

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pos",
            name="money_limit_per_day",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
