# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-22 09:18

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_permissions"),
        ("store", "0002_pos_money_limit_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwipeCardTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_code", models.CharField(max_length=127)),
                ("customer_name", models.CharField(max_length=127)),
                ("customer_gender", models.CharField(max_length=127)),
                ("phone_number", models.CharField(max_length=127)),
                ("customer_money_needed", models.PositiveBigIntegerField(default=0)),
                ("customer_account", models.CharField(max_length=127)),
                ("customer_bank_account", models.CharField(max_length=127)),
                ("card_number", models.CharField(max_length=127)),
                ("card_bank_name", models.CharField(max_length=127)),
                ("line_of_credit", models.PositiveBigIntegerField(default=0)),
                ("fee", models.PositiveBigIntegerField(default=0)),
                ("card_name", models.CharField(max_length=127)),
                ("card_issued_date", models.DateField()),
                ("card_expire_date", models.DateField()),
                ("card_ccv", models.CharField(max_length=127)),
                ("statement_date", models.DateField()),
                ("maturity_date", models.DateField()),
                ("is_payment_received", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipe_card_transaction",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
