# Generated by Django 3.2 on 2023-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_swipecardtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=127)),
                ('card_bank_name', models.CharField(max_length=127)),
                ('card_name', models.CharField(max_length=127)),
                ('card_issued_date', models.DateField()),
                ('card_expire_date', models.DateField()),
                ('card_ccv', models.CharField(max_length=127)),
                ('statement_date', models.DateField()),
                ('maturity_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SwipeCardTransaction',
        ),
    ]
