# Generated by Django 3.2 on 2023-04-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230422_0920'),
        ('store', '0004_auto_20230422_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=127)),
                ('customer_name', models.CharField(max_length=127)),
                ('customer_gender', models.CharField(max_length=127)),
                ('phone_number', models.CharField(max_length=127)),
                ('customer_money_needed', models.PositiveBigIntegerField(default=0)),
                ('customer_account', models.CharField(max_length=127)),
                ('customer_bank_account', models.CharField(max_length=127)),
                ('line_of_credit', models.PositiveBigIntegerField(default=0)),
                ('fee', models.PositiveBigIntegerField(default=0)),
                ('is_payment_received', models.BooleanField(default=False)),
                ('creditcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='store.creditcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='user.user')),
            ],
        ),
    ]
