# Generated by Django 3.2 on 2023-04-27 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230422_0920'),
        ('store', '0005_swipecardtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipecardtransaction',
            name='creditcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='store.creditcard'),
        ),
        migrations.AlterField(
            model_name='swipecardtransaction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='user.user'),
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='store.store')),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='notebook',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditcard', to='store.notebook'),
        ),
    ]
