# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-27 07:54

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_auto_20230427_0735"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebook",
            name="name",
            field=models.CharField(default="Cửa hàng", max_length=127),
        ),
    ]
