# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-27 13:07

from __future__ import absolute_import, print_function, unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_notebook_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipecardtransaction",
            name="transaction_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
