# Generated by Django 3.2 on 2023-04-27 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_swipecardtransaction_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipecardtransaction',
            name='transaction_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
