# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-04-27 13:29

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20230422_0920"),
        ("store", "0009_alter_swipecardtransaction_transaction_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swipecardtransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="swipe_card_transaction", to="user.user"
            ),
        ),
    ]
