# Generated by Django 3.2 on 2023-05-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_swipecardtransaction_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pos',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='swipecardtransaction',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditcard', to='store.notebook'),
        ),
    ]
