# Generated by Django 3.2 on 2023-05-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230503_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditcards', to='store.notebook'),
        ),
    ]
