# Generated by Django 3.2 on 2023-05-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_creditcard_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipecardtransaction',
            name='at_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='store.store'),
        ),
    ]
