# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-20 16:55

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_swipecardtransaction_at_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=127)),
                ("phone_number", models.CharField(max_length=12)),
                ("account_number", models.CharField(max_length=127)),
                ("id_card_image", models.ImageField(upload_to="uploads/% Y/% m/% d/")),
            ],
        ),
    ]
