# Generated by Django 3.2 on 2023-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='card_bank_name',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_ccv',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_expire_date',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_issued_date',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='notebook',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='statement_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_card_image',
            field=models.ImageField(upload_to='uploads///% Y/% m/% d/'),
        ),
    ]
