# Generated by Django 3.2 on 2023-05-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20230521_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipecardtransaction',
            name='creditcard',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
