# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-21 03:17

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_auto_20230521_1016"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(blank=True, max_length=127, null=True)),
                ("card_bank_name", models.CharField(blank=True, max_length=127, null=True)),
                ("card_name", models.CharField(blank=True, max_length=127, null=True)),
                ("card_issued_date", models.DateField(blank=True, null=True)),
                ("card_expire_date", models.DateField(blank=True, null=True)),
                ("card_ccv", models.CharField(blank=True, max_length=127, null=True)),
                ("statement_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("id_card_front_image", models.ImageField(upload_to="uploads/creditcards/% Y/% m/% d/")),
                ("id_card_back_image", models.ImageField(upload_to="uploads/creditcards/% Y/% m/% d/")),
                (
                    "notebook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditcards",
                        to="store.notebook",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="creditcard",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipe_card_transaction",
                to="store.creditcard",
            ),
        ),
    ]
