# Generated by Django 3.2 on 2023-05-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20230521_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='id_card_back_image',
            field=models.ImageField(upload_to='uploads/creditcards/'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id_card_front_image',
            field=models.ImageField(upload_to='uploads/creditcards/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_card_image',
            field=models.ImageField(upload_to='uploads/customer/'),
        ),
        migrations.DeleteModel(
            name='SwipeCardTransaction',
        ),
    ]
