# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-21 03:59

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_auto_20230521_1059"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creditcard",
            old_name="id_card_back_image",
            new_name="credit_card_back_image",
        ),
        migrations.RenameField(
            model_name="creditcard",
            old_name="id_card_front_image",
            new_name="credit_card_front_image",
        ),
    ]
