# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-21 04:08

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_user_options"),
        ("store", "0019_auto_20230521_1059"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="account_number",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name="SwipeCardTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(blank=True, max_length=127, null=True)),
                ("customer_phone_number", models.CharField(blank=True, max_length=12, null=True)),
                ("customer_gender", models.CharField(blank=True, max_length=127, null=True)),
                ("customer_account_number", models.CharField(blank=True, max_length=127, null=True)),
                ("customer_id_card_image", models.ImageField(upload_to="uploads/customer/")),
                ("customer_money_needed", models.PositiveBigIntegerField(default=0)),
                ("customer_account", models.CharField(blank=True, max_length=127, null=True)),
                ("customer_bank_account", models.CharField(blank=True, max_length=127, null=True)),
                ("line_of_credit", models.PositiveBigIntegerField(default=0)),
                ("fee", models.PositiveBigIntegerField(default=0)),
                ("is_payment_received", models.BooleanField(default=False)),
                ("transaction_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "at_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipe_card_transaction",
                        to="store.store",
                    ),
                ),
                (
                    "creditcard",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipe_card_transaction",
                        to="store.creditcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swipe_card_transaction",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
