# Generated by Django 3.2 on 2023-05-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20230521_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwipeCardTransaction',
        ),
    ]
