# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-22 15:26

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_swipecardtransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="SwipeCardTransaction",
        ),
    ]
