# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-24 02:20

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_swipecardtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
