# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-24 03:32

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_creditcard_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillPos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_id", models.PositiveBigIntegerField()),
                ("bill_image", models.ImageField(upload_to="uploads/billpos/")),
                ("total_money", models.PositiveBigIntegerField()),
                ("batch", models.CharField(blank=True, max_length=128, null=True)),
                ("invoice", models.CharField(blank=True, max_length=128, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=128, null=True)),
                ("approve_code", models.CharField(blank=True, max_length=128, null=True)),
                ("datetime_bill", models.DateTimeField()),
                ("note", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StoreCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("electricity_bill", models.BigIntegerField(default=0)),
                ("water_bill", models.BigIntegerField(default=0)),
                ("surcharge", models.BigIntegerField(default=0)),
                ("rental_costs", models.BigIntegerField(default=0)),
                ("date", models.DateField()),
                (
                    "store_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="storecost", to="store.store"
                    ),
                ),
            ],
        ),
    ]
