# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-25 03:09

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_billpos_storecost"),
    ]

    operations = [
        migrations.CreateModel(
            name="RowNotebook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=128)),
                ("storage_datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("closing_balance", models.BigIntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="row_notebook", to="store.notebook"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="notebook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditcards",
                to="store.rownotebook",
            ),
        ),
    ]
