# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-05-25 05:25

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_auto_20230525_1009"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("price", models.BigIntegerField(default=0)),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
    ]
