# Generated by Django 3.2 on 2023-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rownotebook',
            options={'ordering': ['-storage_datetime']},
        ),
        migrations.AddField(
            model_name='creditcard',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
