# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-20 07:26

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_auto_20230614_2247"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SwipeCardTransaction",
        ),
    ]
