# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-20 14:25

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0031_swipecardtransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pos",
            name="status",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
