# Generated by Django 3.2 on 2023-06-21 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20230620_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipecardtransaction',
            name='last_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
