# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-21 03:42

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_swipecardtransaction_last_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="last_date",
        ),
    ]
