# Generated by Django 3.2 on 2023-06-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_swipecardtransaction_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipecardtransaction',
            name='last_date',
        ),
    ]
