# Generated by Django 3.2 on 2023-06-21 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_swipecardtransaction_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rownotebook',
            name='last_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
