# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-22 00:29

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_rownotebook_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="status",
            field=models.IntegerField(choices=[(1, "Đang hoạt động"), (2, "Tạm dừng"), (3, "Đóng")], default=1),
        ),
    ]
