# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-22 16:14

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0036_alter_pos_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Đang hoạt động"), (2, "Tạm dừng"), (3, "Đóng")], default=1
            ),
        ),
    ]
