# Generated by Django 3.2 on 2023-06-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_pos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rownotebook',
            name='last_date',
        ),
    ]
