# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-23 06:53

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_remove_rownotebook_last_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="rownotebook",
            name="last_date",
            field=models.IntegerField(default=0),
        ),
    ]
