# Generated by Django 3.2 on 2023-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_rownotebook_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/creditcards/'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/creditcards/'),
        ),
    ]
