# Generated by Django 3.2 on 2023-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20230624_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipecardtransaction',
            name='is_creditcard_stored',
            field=models.BooleanField(default=False),
        ),
    ]
