# Generated by Django 3.2 on 2023-06-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_swipecardtransaction_is_creditcard_stored'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
        migrations.DeleteModel(
            name='SwipeCardTransaction',
        ),
    ]
