# Generated by Django 3.2 on 2023-06-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_infomationdetail_gender'),
        ('store', '0042_auto_20230626_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.CreateModel(
            name='SwipeCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creditcard_stored', models.BooleanField(default=False)),
                ('store_id', models.PositiveBigIntegerField()),
                ('store_code', models.CharField(max_length=127)),
                ('store_name', models.CharField(max_length=127)),
                ('store_note', models.TextField(blank=True, null=True)),
                ('store_address', models.CharField(max_length=1023)),
                ('store_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=127, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('customer_gender', models.CharField(blank=True, max_length=127, null=True)),
                ('customer_account_number', models.CharField(blank=True, max_length=127, null=True)),
                ('customer_id_card_front_image', models.ImageField(blank=True, null=True, upload_to='uploads/customer/')),
                ('customer_id_card_back_image', models.ImageField(blank=True, null=True, upload_to='uploads/customer/')),
                ('bill_pos_image', models.ImageField(upload_to='uploads/pos/')),
                ('customer_money_needed', models.PositiveBigIntegerField(default=0)),
                ('customer_account', models.CharField(blank=True, max_length=127, null=True)),
                ('customer_bank_account', models.CharField(blank=True, max_length=127, null=True)),
                ('line_of_credit', models.PositiveBigIntegerField(default=0)),
                ('fee', models.PositiveBigIntegerField(default=0)),
                ('is_payment_received', models.BooleanField(default=False)),
                ('transaction_datetime_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_datetime_updated', models.DateTimeField(auto_now=True)),
                ('at_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='store.store')),
                ('creditcard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='store.creditcard')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='store.pos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_card_transaction', to='user.user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
