# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-26 05:16

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0043_auto_20230626_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="notebook",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditcards",
                to="store.rownotebook",
            ),
        ),
    ]
