# Generated by Django 3.2 on 2023-06-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_alter_creditcard_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='rownotebook',
            name='card_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
