# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-26 14:29

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0045_rownotebook_card_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="is_payment_received",
        ),
        migrations.AddField(
            model_name="creditcard",
            name="is_payment_received",
            field=models.BooleanField(default=False),
        ),
    ]
