# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-06-29 16:48

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0046_auto_20230626_2129"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="is_expired",
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="transaction_type",
            field=models.SmallIntegerField(choices=[(1, "Rút tiền"), (2, "TĐáo thẻ")], default=1),
        ),
    ]
