# Generated by Django 3.2 on 2023-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20230629_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
