# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-02 07:01

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0048_notebook_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="rownotebook",
            name="order_in_notebook",
            field=models.IntegerField(default=1),
        ),
    ]
