# Generated by Django 3.2 on 2023-07-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_rownotebook_order_in_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipecardtransaction',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(1, 'Rút tiền'), (2, 'Đáo thẻ')], default=1),
        ),
    ]
