# Generated by Django 3.2 on 2023-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_swipecardtransaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='is_payment_received',
        ),
        migrations.AddField(
            model_name='swipecardtransaction',
            name='is_payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
