# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-10 08:06

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0051_auto_20230709_0009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pos",
            name="pos_id",
        ),
    ]
