# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-11 09:13

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0052_remove_pos_pos_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_gender",
        ),
    ]
