# Generated by Django 3.2 on 2023-07-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_remove_pos_pos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipecardtransaction',
            name='customer_gender',
        ),
    ]
