# Generated by Django 3.2 on 2023-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_remove_swipecardtransaction_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipecardtransaction',
            name='customer_gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nam'), (2, 'Nữ'), (3, 'Khác')], default=3),
        ),
    ]
