# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-12 00:01

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0054_swipecardtransaction_customer_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="creditcard",
        ),
        migrations.DeleteModel(
            name="CreditCard",
        ),
    ]
