# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-12 00:01

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0055_auto_20230712_0701"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(max_length=127, unique=True)),
                ("card_bank_name", models.CharField(blank=True, max_length=127, null=True)),
                ("card_name", models.CharField(blank=True, max_length=127, null=True)),
                ("card_issued_date", models.DateField(blank=True, null=True)),
                ("card_expire_date", models.DateField(blank=True, null=True)),
                ("card_ccv", models.CharField(blank=True, max_length=127, null=True)),
                ("statement_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("credit_card_front_image", models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/")),
                ("credit_card_back_image", models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/")),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "notebook",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditcards",
                        to="store.rownotebook",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="creditcard",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipe_card_transaction",
                to="store.creditcard",
            ),
        ),
    ]
