# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-12 16:40

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0056_auto_20230712_0701"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swipecardtransaction",
            name="creditcard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipe_card_transaction",
                to="store.creditcard",
            ),
        ),
    ]
