# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-19 17:17

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("store", "0057_alter_swipecardtransaction_creditcard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="notebook",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="creditcard",
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipe_card_transaction",
                to="customer.customer",
            ),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="datetime_bill",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name="CreditCard",
        ),
    ]
