# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-19 23:30

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0058_auto_20230720_0017"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BillPos",
        ),
    ]
