# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-19 23:30

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0059_delete_billpos"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillPos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bill_image", models.ImageField(upload_to="uploads/billpos/")),
                ("total_money", models.PositiveBigIntegerField(blank=True, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=128, null=True)),
                ("invoice_no", models.CharField(blank=True, max_length=128, null=True)),
                ("batch", models.CharField(blank=True, max_length=128, null=True)),
                ("authorization_code", models.CharField(blank=True, max_length=128, null=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "pos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="billposes", to="store.pos"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billposes",
                        to="store.swipecardtransaction",
                    ),
                ),
            ],
        ),
    ]
