# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-20 09:37

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0060_billpos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="bill_pos_image",
        ),
    ]
