# Generated by Django 3.2 on 2023-07-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_remove_swipecardtransaction_bill_pos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipecardtransaction',
            name='pos',
        ),
    ]
