# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-21 14:57

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0062_remove_swipecardtransaction_pos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_account",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_bank_account",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="line_of_credit",
        ),
    ]
