# Generated by Django 3.2 on 2023-07-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_auto_20230721_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipecardtransaction',
            name='negative_money',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
