# Generated by Django 3.2 on 2023-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_swipecardtransaction_negative_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billpos',
            old_name='datetime',
            new_name='datetime_created',
        ),
        migrations.AddField(
            model_name='billpos',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
