# Generated by Django 3.2 on 2023-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_auto_20230722_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipecardtransaction',
            name='is_payment_received',
        ),
        migrations.AddField(
            model_name='billpos',
            name='is_payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
