# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 02:27

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0066_auto_20230722_1546"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billpos",
            options={"ordering": ["-datetime_created"]},
        ),
    ]
