# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 03:10

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0067_alter_billpos_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipecardtransaction",
            name="credit_card_number",
            field=models.CharField(db_index=True, default="1", max_length=20),
        ),
    ]
