# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 04:44

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0069_alter_swipecardtransaction_credit_card_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notebook",
            old_name="capacity",
            new_name="capacity_per_page",
        ),
        migrations.AddField(
            model_name="notebook",
            name="pages",
            field=models.IntegerField(default=0),
        ),
    ]
