# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 17:49

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0070_auto_20230723_1144"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_account_number",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_gender",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_phone_number",
        ),
        migrations.AddField(
            model_name="pos",
            name="from_store",
            field=models.ForeignKey(
                default=7, on_delete=django.db.models.deletion.CASCADE, related_name="provide_poses", to="store.store"
            ),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="authorization_code",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="batch",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="invoice_no",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="ref_no",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="pos",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="rownotebook",
            name="card_location",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="rownotebook",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="store",
            name="note",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="store",
            name="phone_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="swipecardtransaction",
            name="store_note",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="swipecardtransaction",
            name="store_phone_number",
            field=models.CharField(default="", max_length=20),
        ),
    ]
