# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 17:49

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0071_auto_20230724_0049"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="business_license_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/store/"),
        ),
        migrations.AddField(
            model_name="store",
            name="representative_id_card_front_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/store/"),
        ),
        migrations.AddField(
            model_name="store",
            name="representative_s_name",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AddField(
            model_name="store",
            name="representative_s_phone_number",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AddField(
            model_name="store",
            name="tax_code",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AddField(
            model_name="store",
            name="working_status",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AlterField(
            model_name="pos",
            name="from_store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="provide_poses", to="store.store"
            ),
        ),
    ]
