# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 18:02

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0072_auto_20230724_0049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
