# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 18:03

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0073_alter_store_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="representative_s_name",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name="store",
            name="representative_s_phone_number",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name="store",
            name="tax_code",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name="store",
            name="working_status",
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
