# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 18:08

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0074_auto_20230724_0103"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="representative_id_card_back_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/store/"),
        ),
    ]
