# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 04:34

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0075_store_representative_id_card_back_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notebook",
            old_name="pages",
            new_name="capacity",
        ),
    ]
