# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 07:26

from __future__ import absolute_import, print_function, unicode_literals
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0076_rename_pages_notebook_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="rownotebook",
            name="card_given_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="rownotebook",
            name="card_taken_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
