# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 17:13

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0077_auto_20230724_1426"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreMakePOS",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=127)),
                ("name", models.CharField(max_length=127)),
                ("note", models.TextField(blank=True)),
                ("address", models.CharField(max_length=1023)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("tax_code", models.CharField(blank=True, max_length=127)),
                ("representative_s_name", models.CharField(blank=True, max_length=127)),
                ("representative_s_phone_number", models.CharField(blank=True, max_length=127)),
                ("working_status", models.CharField(blank=True, max_length=127)),
                ("business_license_image", models.ImageField(blank=True, null=True, upload_to="uploads/store/")),
                (
                    "representative_id_card_front_image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/store/"),
                ),
                (
                    "representative_id_card_back_image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/store/"),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RemoveField(
            model_name="pos",
            name="from_store",
        ),
        migrations.RemoveField(
            model_name="store",
            name="business_license_image",
        ),
        migrations.RemoveField(
            model_name="store",
            name="representative_id_card_back_image",
        ),
        migrations.RemoveField(
            model_name="store",
            name="representative_id_card_front_image",
        ),
        migrations.RemoveField(
            model_name="store",
            name="representative_s_name",
        ),
        migrations.RemoveField(
            model_name="store",
            name="representative_s_phone_number",
        ),
        migrations.RemoveField(
            model_name="store",
            name="tax_code",
        ),
        migrations.RemoveField(
            model_name="store",
            name="working_status",
        ),
    ]
