# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 17:14

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0078_auto_20230725_0013"),
    ]

    operations = [
        migrations.AddField(
            model_name="pos",
            name="from_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poses",
                to="store.storemakepos",
            ),
        ),
    ]
