# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 18:33

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0079_pos_from_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storemakepos",
            name="working_status",
        ),
    ]
