# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 18:34

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0080_remove_storemakepos_working_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="storemakepos",
            name="working_status",
            field=models.SmallIntegerField(choices=[(1, "Đang hoạt động"), (2, "Tạm dừng"), (3, "Đóng")], default=1),
        ),
    ]
