# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-24 18:44

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0081_storemakepos_working_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rownotebook",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "Đang lưu thẻ"), (2, "Đã trả thẻ")], default=1),
        ),
    ]
