# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-25 16:37

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0082_alter_rownotebook_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="code",
        ),
        migrations.RemoveField(
            model_name="storemakepos",
            name="business_license_image",
        ),
        migrations.RemoveField(
            model_name="storemakepos",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="storemakepos",
            name="tax_code",
        ),
        migrations.AddField(
            model_name="store",
            name="contract_of_house_renting_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/store/"),
        ),
        migrations.AddField(
            model_name="store",
            name="electric_bill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="store",
            name="rent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="store",
            name="surcharge",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="store",
            name="water_bill",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="storemakepos",
            name="business_license_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/storemakepos/"),
        ),
        migrations.AddField(
            model_name="storemakepos",
            name="tax_code_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/storemakepos/"),
        ),
        migrations.AlterField(
            model_name="storemakepos",
            name="representative_id_card_back_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/storemakepos/"),
        ),
        migrations.AlterField(
            model_name="storemakepos",
            name="representative_id_card_front_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/storemakepos/"),
        ),
        migrations.AlterField(
            model_name="storemakepos",
            name="working_status",
            field=models.SmallIntegerField(choices=[(1, "Đã đóng GPKD"), (2, "Chưa đóng GPKD")], default=2),
        ),
    ]
