# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-25 17:02

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0083_auto_20230725_2337"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storemakepos",
            name="code",
        ),
    ]
