# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 06:32

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0084_remove_storemakepos_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
