# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 09:11

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0085_alter_pos_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="store_code",
        ),
    ]
