# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 11:30

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0086_remove_swipecardtransaction_store_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="store_note",
        ),
    ]
