# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 11:47

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0087_remove_swipecardtransaction_store_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billpos",
            name="authorization_code",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="batch",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="billpos",
            name="ref_no",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
