# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 18:35

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0088_auto_20230726_1847"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeePos4CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mid", models.CharField(max_length=127)),
                ("fee", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="pos",
            name="account_number",
            field=models.CharField(default="", max_length=24),
        ),
        migrations.AddField(
            model_name="pos",
            name="money_limit_per_time",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pos",
            name="name",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AddField(
            model_name="pos",
            name="phone_number",
            field=models.CharField(default="", max_length=24),
        ),
        migrations.AddField(
            model_name="pos",
            name="fee",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pos",
                to="store.feepos4creditcard",
            ),
        ),
    ]
