# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 18:35

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0089_auto_20230727_0135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="account_number",
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name="pos",
            name="name",
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name="pos",
            name="phone_number",
            field=models.CharField(max_length=24),
        ),
    ]
