# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 18:36

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0091_pos_bank_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pos",
            name="bank_account",
            field=models.CharField(max_length=127),
        ),
    ]
