# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 18:42

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0092_alter_pos_bank_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feepos4creditcard",
            old_name="mid",
            new_name="type",
        ),
    ]
