# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 19:02

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0093_rename_mid_feepos4creditcard_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pos",
            name="account_number",
        ),
    ]
