# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-27 09:54

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0094_remove_pos_account_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_id_card_back_image",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer_id_card_front_image",
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="transaction_with_customer_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/swipecard_transaction/"),
        ),
    ]
