# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-27 10:52

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0095_auto_20230727_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="billpos",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
