# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-27 11:01

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0096_billpos_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pos",
            name="fee",
        ),
        migrations.DeleteModel(
            name="FeePos4CreditCard",
        ),
    ]
