# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-27 11:02

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0097_auto_20230727_1801"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeePos4CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=127)),
                ("fee", models.FloatField()),
                (
                    "pos_machine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="fee4creditcard", to="store.pos"
                    ),
                ),
            ],
        ),
    ]
