# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-28 12:20

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0098_feepos4creditcard"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feepos4creditcard",
            options={"ordering": ["-id"]},
        ),
    ]
