# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-07-31 10:03

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0099_alter_feepos4creditcard_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepos4creditcard",
            name="pos_machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="fee4creditcard", to="store.pos"
            ),
        ),
    ]
