# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-07-31 18:00

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0100_alter_feepos4creditcard_pos_machine"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feepos4creditcard",
            options={"ordering": ["id"]},
        ),
    ]
