# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-01 18:13

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0101_alter_feepos4creditcard_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rownotebook",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
