# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-04 09:32

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0103_auto_20230804_1631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billpos",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "Tiền chưa về"), (2, "Tiền đã về"), (3, "Sai Bill"), (4, "Huỷ Bill")], default=1
            ),
        ),
    ]
