# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-04 16:43

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_creditcard"),
        ("store", "0104_alter_billpos_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="credit_card_number",
        ),
        migrations.RemoveField(
            model_name="swipecardtransaction",
            name="customer",
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="creditcard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipe_card_transaction",
                to="customer.creditcard",
            ),
        ),
    ]
