# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-05 05:27

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0105_auto_20230804_2343"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rownotebook",
            name="status",
        ),
        migrations.AddField(
            model_name="rownotebook",
            name="update_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="rownotebook",
            name="storage_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
