# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-09 06:27

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0106_auto_20230805_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipecardtransaction",
            name="toll_status",
            field=models.SmallIntegerField(choices=[(1, "Đã thu"), (2, "Chưa thu")], default=1),
        ),
    ]
