# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-17 15:14

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0107_swipecardtransaction_toll_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billpos",
            name="status",
        ),
        migrations.AddField(
            model_name="billpos",
            name="receive_money",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="billpos",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
