# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-28 15:16

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0108_auto_20230817_2214"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipecardtransaction",
            name="account_number",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AddField(
            model_name="swipecardtransaction",
            name="bank_name",
            field=models.CharField(max_length=127, null=True),
        ),
    ]
