# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-09-26 17:25

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0016_auto_20230827_2100"),
        ("store", "0109_auto_20230828_2216"),
    ]

    operations = [
        migrations.AddField(
            model_name="swipecardtransaction",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swipe_card_transaction",
                to="customer.customer",
            ),
        ),
    ]
