import { ADMIN, EMPLOYEE } from "./constants";
export const dataItemSideBarForEmployee = [
  {
    id: 5,
    name: "Thống kê giao dịch",
    icon: "chart-bar",
    path: "/dashboard/reportemp",
    role: [EMPLOYEE],
  },
  {
    id: 6,
    name: "Bill máy POS",
    icon: "money-bill",
    path: "/dashboard/billposmanage",
    role: [ADMIN, EMPLOYEE],
  },
  {
    id: 7,
    name: "Hoá đơn",
    icon: "file-invoice",
    path: "/dashboard/stores3",
    role: [ADMIN, EMPLOYEE],
  },
  {
    id: 8,
    name: "Quẹt thẻ",
    icon: "credit-card",
    path: "/dashboard/swipecard",
    role: [ADMIN, EMPLOYEE],
  },
  {
    id: 9,
    name: "Lưu thẻ",
    icon: "box",
    path: "/dashboard/storecard",
    role: [ADMIN, EMPLOYEE],
  },
  // {
  //   id: 10,
  //   name: "Danh sách thẻ đã lưu",
  //   icon: "list",
  //   path: "/dashboard/savedcard",
  //   role: [ADMIN, EMPLOYEE],
  // },
  // {
  //   id: 11,
  //   name: "Lịch sử quẹt thẻ",
  //   icon: (
  //     <FontAwesomeIcon
  //       icon={icon({ name: "clock-rotate-left", style: "solid" })}
  //     />
  //   ),
  //   path: "/dashboard/transaction-history",
  //   role: [ADMIN, EMPLOYEE],
  // },
];
export const dataItemSideBarForAdmin = [
  {
    id: 0,
    name: "CH máy POS",
    icon: "store",
    path: "/dashboard/storesmakepos",
    role: [ADMIN],
    private: true,
  },
  {
    id: 1,
    name: "Cửa hàng ",
    icon: "store",
    path: "/dashboard/stores",
    role: [ADMIN],
    private: true,
  },
  {
    id: 2,
    name: "Máy POS",
    icon: "cash-register",
    path: "/dashboard/poses",
    role: [ADMIN],
    private: true,
  },
  {
    id: 3,
    name: "Sổ lưu thẻ",
    icon: "book-open",
    path: "/dashboard/notebooks",
    role: [ADMIN],
    private: true,
  },
  {
    id: 4,
    name: "Nhân viên",
    icon: "users",
    path: "/dashboard/employees",
    role: [ADMIN],
    private: true,
  },
  {
    id: 6,
    name: "Q.lý Bill máy POS",
    icon: "receipt",
    path: "/dashboard/billposmanage",
    role: [ADMIN, EMPLOYEE],
  },
  {
    id: 7,
    name: "Hoá đơn",
    icon: "file-invoice",
    path: "/dashboard/stores3",
    role: [ADMIN, EMPLOYEE],
  },
  {
    id: 8,
    name: "Quẹt thẻ",
    icon: "credit-card",
    path: "/dashboard/swipecard",
    role: [ADMIN, EMPLOYEE],
  },
  {
    id: 9,
    name: "Lưu thẻ",
    icon: "box",
    path: "/dashboard/storecard",
    role: [ADMIN, EMPLOYEE],
  },
  // {
  //   id: 10,
  //   name: "Thẻ đã lưu",
  //   icon: "list",
  //   path: "/dashboard/savedcard",
  //   role: [ADMIN, EMPLOYEE],
  // },
  {
    id: 12,
    name: "Sản phẩm",
    icon: "boxes",
    path: "/dashboard/products",
    role: [ADMIN],
  },
  {
    id: 13,
    name: "Thống kê",
    icon: "chart-bar",
    path: "/dashboard/reportadm",
    role: [ADMIN],
    private: true,
  },
  {
    id: 14,
    name: "Quản lý thẻ",
    icon: "id-card",
    path: "/dashboard/creditcardmanagement",
    role: [ADMIN],
    private: true,
  },
  {
    id: 15,
    name: "Quản lý KH",
    icon: "user-tie",
    path: "/dashboard/customermanagement",
    role: [ADMIN],
    private: true,
  },
];
