# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-19 17:17

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0057_alter_swipecardtransaction_creditcard"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_number", models.CharField(max_length=127)),
                ("bank_name", models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(max_length=127, unique=True)),
                ("card_bank_name", models.CharField(blank=True, max_length=127, null=True)),
                ("card_name", models.CharField(blank=True, max_length=127, null=True)),
                ("card_issued_date", models.DateField(blank=True, null=True)),
                ("card_expire_date", models.DateField(blank=True, null=True)),
                ("card_ccv", models.CharField(blank=True, max_length=127, null=True)),
                ("statement_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("credit_card_front_image", models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/")),
                ("credit_card_back_image", models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/")),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "notebook",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditcards",
                        to="store.rownotebook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=127, null=True)),
                ("phone_number", models.CharField(max_length=12, unique=True)),
                ("gender", models.CharField(blank=True, max_length=127, null=True)),
                ("id_card_front_image", models.ImageField(blank=True, null=True, upload_to="uploads/customer/")),
                ("id_card_back_image", models.ImageField(blank=True, null=True, upload_to="uploads/customer/")),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="customer.bankaccount",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="customer", to="customer.creditcard"
                    ),
                ),
            ],
        ),
    ]
