# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-21 06:32

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="gender",
        ),
    ]
