# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-21 06:32

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_customer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.PositiveSmallIntegerField(choices=[(1, "Nam"), (2, "Nữ"), (3, "Khác")], default=3),
        ),
    ]
