# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-21 14:57

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="line_of_credit",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
