# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 03:10

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_creditcard_line_of_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="card_ccv",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="card_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
