# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-23 17:28

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_auto_20230723_1010"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="card_bank_name",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="card_ccv",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="card_name",
            field=models.CharField(default="", max_length=127),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(default="", max_length=127),
        ),
    ]
