# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 11:07

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_auto_20230724_0028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="card_bank_name",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="card_ccv",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="card_name",
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
