# -*- coding: utf-8 -*-
# Generated by Django 3.2 on 2023-07-26 11:31

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_auto_20230726_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
