# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-04 16:12

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="credit_card",
        ),
        migrations.DeleteModel(
            name="CreditCard",
        ),
    ]
