# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-04 16:14

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0104_alter_billpos_status"),
        ("customer", "0009_auto_20230804_2312"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(max_length=20, unique=True)),
                ("card_bank_name", models.CharField(blank=True, max_length=127)),
                ("card_name", models.CharField(blank=True, max_length=127)),
                ("card_issued_date", models.DateField(blank=True, null=True)),
                ("card_expire_date", models.DateField(blank=True, null=True)),
                ("card_ccv", models.CharField(blank=True, max_length=3)),
                ("statement_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("credit_card_front_image", models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/")),
                ("credit_card_back_image", models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/")),
                ("note", models.TextField(blank=True, default="")),
                ("line_of_credit", models.PositiveBigIntegerField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="creditcard", to="customer.customer"
                    ),
                ),
                (
                    "notebook",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditcards",
                        to="store.rownotebook",
                    ),
                ),
            ],
        ),
    ]
