# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-04 18:04

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0105_auto_20230804_2343"),
        ("customer", "0010_creditcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="notebook",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creditcard",
                to="store.rownotebook",
            ),
        ),
    ]
