# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-05 05:27

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_alter_creditcard_notebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="maturity_status",
            field=models.SmallIntegerField(choices=[(1, "Đang lưu thẻ"), (2, "Đã trả thẻ")], default=1),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="storage_status",
            field=models.SmallIntegerField(choices=[(1, "Đang lưu thẻ"), (2, "Đã trả thẻ")], default=1),
        ),
    ]
