# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-20 02:04

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_auto_20230805_1227"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-id"]},
        ),
    ]
