# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-27 13:13

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_alter_customer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="id_card_back_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/"),
        ),
        migrations.AddField(
            model_name="creditcard",
            name="id_card_front_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/creditcards/"),
        ),
    ]
