# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-27 13:33

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_auto_20230827_2013"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="bank_account",
        ),
    ]
