# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-08-27 14:00

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0015_remove_customer_bank_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id_card_back_image",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="id_card_front_image",
        ),
    ]
