# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-09-27 12:40

from __future__ import absolute_import, print_function, unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0016_auto_20230827_2100"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="notebook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="customer.bankaccount",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
