# -*- coding: utf-8 -*-
# Generated by Django 3.2.20 on 2023-09-27 12:47

from __future__ import absolute_import, print_function, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0017_auto_20230927_1940"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="notebook",
            new_name="bank_account",
        ),
    ]
